{{- $values := $.Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-service.fullname" . }}-headless
  labels:
    {{- include "file-service.labels" . | nindent 4 }}
spec:
  clusterIP: None # Headless service
  ports: []
  selector:
    {{- include "file-service.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $values.service.topologyAwareRouting.enabled }}
  annotations:
    {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.GitVersion }}
    service.kubernetes.io/topology-mode: "auto"
    {{- else }}
    service.kubernetes.io/topology-aware-hints: "auto"
    {{- end }}
  {{- end }}
  name: {{ include "file-service.fullname" . }}
  labels:
    {{- include "file-service.labels" . | nindent 4 }}
    serviceMonitorTarget: "true"  # Additional label to prevent matching the headless service above
spec:
  type: {{ $values.service.type }}
  ports:
  {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    {{- include "file-service.selectorLabels" . | nindent 4 }}
