{{- $values := $.Values.lighthouse }}
{{- $componentName := "lighthouse" }}
{{- $componentLabel := include "lighthouse.componentLabelFor" $componentName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse.fullname" . }}-{{ $componentName }}-headless
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  clusterIP: None # Headless service
  ports:
  {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    {{- include "lighthouse.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $values.service.topologyAwareRouting.enabled }}
  annotations:
    {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.GitVersion }}
    service.kubernetes.io/topology-mode: "auto"
    {{- else }}
    service.kubernetes.io/topology-aware-hints: "auto"
    {{- end }}
  {{- end }}
  name: {{ include "lighthouse.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
    serviceMonitorTarget: "true"  # Additional label to prevent matching the headless service above
spec:
  type: {{ $values.service.type }}
  ports:
    - name: http-lighthouse
      port: {{ index $values.service.ports "http-lighthouse" }}
      targetPort: http-lighthouse
      protocol: TCP
    - name: http-metrics
      port: {{ index $values.service.ports "http-metrics" }}
      targetPort: http-metrics
      protocol: TCP
    {{- if not $values.p2pNodePort.enabled }}
    - name: tcp-transport
      port: {{ include "lighthouse.port" $values }}
      targetPort: tcp-transport
      protocol: TCP
    - name: udp-discovery
      port: {{ include "lighthouse.discoveryPort" $values }}
      targetPort: udp-discovery
      protocol: UDP
    - name: udp-transport
      port: {{ include "lighthouse.quicPort" $values }}
      targetPort: udp-transport
      protocol: UDP
    {{- end }}
  selector:
    {{- include "lighthouse.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
{{- if $values.p2pNodePort.enabled }}
{{- $port := $values.p2pNodePort.port }}
{{- $quicPort := add $values.p2pNodePort.port 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse.fullname" . }}-{{ $componentName }}-p2p-0
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
    pod: {{ include "lighthouse.fullname" . }}-{{ $componentName }}-0
    type: p2p # this label is used by the initContainer to select this service
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: tcp-transport
      port: {{ $port }}
      protocol: TCP
      targetPort: tcp-transport
      nodePort: {{ $port }}
    - name: udp-discovery
      port: {{ $port }}
      protocol: UDP
      targetPort: udp-discovery
      nodePort: {{ $port }}
    - name: udp-transport
      port: {{ $quicPort }}
      protocol: UDP
      targetPort: udp-transport
      nodePort: {{ $quicPort }}
  selector:
    {{- include "lighthouse.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "lighthouse.fullname" $ }}-{{ $componentName }}-0"
{{- end }}
