{{- if $.Values.jwt.fromLiteral }}
---
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ include "reth.fullname" . }}-jwt
  labels:
    {{- include "reth.labels" . | nindent 4 }}
data:
  jwt.hex: {{ $.Values.jwt.fromLiteral | b64enc }}
{{- end }}