apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" . }}
  labels:
    {{- include "reth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "reth.p2pPort" . }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ include "reth.p2pPort" . }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: {{ .Values.httpPort }}
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: {{ .Values.authPort }}
      targetPort: auth-rpc
      protocol: TCP
      name: auth-rpc
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if ne .Values.httpPort .Values.wsPort }}
    - port: {{ .Values.wsPort }}
      targetPort: ws-rpc
      protocol: TCP
      name: ws-rpc
    {{- end }}
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "reth.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" . }}-headless
  labels:
    {{- include "reth.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "reth.p2pPort" . }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ include "reth.p2pPort" . }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: {{ .Values.httpPort }}
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: {{ .Values.authPort }}
      targetPort: auth-rpc
      protocol: TCP
      name: auth-rpc
    {{- if ne .Values.httpPort .Values.wsPort }}  
    - port: {{ .Values.wsPort }}
      targetPort: ws-rpc
      protocol: TCP
      name: ws-rpc
    {{- end }}
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "reth.selectorLabels" . | nindent 4 }}
---
{{- if .Values.p2pNodePort.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" $ }}-p2p-0
  labels:
    {{- include "reth.labels" $ | nindent 4 }}
    pod: {{ include "reth.fullname" $ }}-0
    type: p2p
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp
      port: {{ include "reth.p2pPort" $ }}
      protocol: TCP
      targetPort: p2p-tcp
      nodePort: {{ include "reth.p2pPort" $ }}
    - name: p2p-udp
      port: {{ include "reth.p2pPort" $ }}
      protocol: UDP
      targetPort: p2p-udp
      nodePort: {{ include "reth.p2pPort" $ }}
  selector:
    {{- include "reth.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "reth.fullname" $ }}-0"
{{- end }}

